version: '3'

services:
  bird-router:
    image: bird-router
    build:
      context: containers/bird
    network_mode: host
    cap_add:
    - NET_ADMIN
    volumes:
    - ./bird.conf:/etc/bird/bird.conf
