version: '3'

networks:
  management:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.0.0/24

services:
  mgmt: &bird
    container_name: mgmt
    image: mgmt
    build:
      context: containers/mgmt
    networks:
    - management
    hostname: mgmt
    command: sh -c 'while true; do sleep 1; done'
    
  edge-0: &router
    image: bird-router
    build:
      context: containers/bird
    networks:
    - management
    container_name: edge-0
    hostname: edge-0
  edge-1:
    <<: *router
    container_name: edge-1
    hostname: edge-1

  spine-0:
    <<: *router
    container_name: spine-0
    hostname: spine-0
  spine-1:
    <<: *router
    container_name: spine-1
    hostname: spine-1
  spine-2:
    <<: *router
    container_name: spine-2
    hostname: spine-2
  spine-3:
    <<: *router
    container_name: spine-3
    hostname: spine-3

  leaf-0:
    <<: *router
    container_name: leaf-0
    hostname: leaf-0
  leaf-1:
    <<: *router
    container_name: leaf-1
    hostname: leaf-1

  leaf-2:
    <<: *router
    container_name: leaf-2
    hostname: leaf-2
  leaf-3:
    <<: *router
    container_name: leaf-3
    hostname: leaf-3

  leaf-4:
    <<: *router
    container_name: leaf-4
    hostname: leaf-4
  leaf-5:
    <<: *router
    container_name: leaf-5
    hostname: leaf-5
