- name: bgp | prepare container directory
  become: yes
  file:
    path: /opt/containers/bird
    state: directory

- name: bgp | render bird.conf
  become: yes
  template:
    src: "{{ role_path }}/../base/templates/bird_{{ router_role }}.conf.j2"
    dest: /opt/containers/bird/bird.conf
  vars:
    bgp: "{{ hostvars[inventory_hostname].bgp }}"
    ibgp: "{{ hostvars[inventory_hostname].ibgp }}"
  register: config
