# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [
  'edge-0',
  'edge-1',

  'spine-0',
  'spine-1',

  'leaf-0',
  'leaf-1',
  'leaf-2',

  'machine-0',
  'machine-1',
  'machine-2',
  'machine-3',
  'machine-4',
  'machine-5',
]

image = 'generic/ubuntu1804'
subnet = '192.168.60'
ip_starts = 11

Vagrant.configure('2') do |config|
  hosts.each_with_index do |host, idx|
    host_ip = "#{subnet}.#{ip_starts + idx}"

    config.vm.define host do |node|
      node.vm.box = image

      node.vm.hostname = host
      node.vm.network 'private_network', ip: host_ip

      config.vm.provider 'virtualbox' do |vb|
        vb.cpus = '1'
        vb.memory = '256'
        vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
        vb.customize ['modifyvm', :id, '--cpuexecutioncap', '50']
      end
    end
  end
end
